// AUTOGENERATED FILE
// This file was generated from addmul.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface AddMulActionDict<T> extends BaseActionDict<T> {
  Expr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Add_plus?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  Add?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Mul_times?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  Mul?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Pri_paren?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  Pri?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  number?: (this: NonterminalNode, arg0: IterationNode) => T;
}

export interface AddMulSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: AddMulActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: AddMulActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: AddMulActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: AddMulActionDict<T>): this;
}

export interface AddMulGrammar extends Grammar {
  createSemantics(): AddMulSemantics;
  extendSemantics(superSemantics: AddMulSemantics): AddMulSemantics;
}

declare const grammar: AddMulGrammar;
export default grammar;

